export enum ButtonVariants {
  PRIMARY = 'primary',
  PRIMARY_EMPTY = 'primaryEmpty',
  SECONDARY = 'secondary',
  SECONDARY_EMPTY = 'secondaryEmpty',
  SUCCESS = 'success',
  SUCCESS_EMPTY = 'successEmpty',
  INFO = 'info',
  INFO_EMPTY = 'infoEmpty',
  WARNING = 'warning',
  WARNING_EMPTY = 'warningEmpty',
  DANGER_EMPTY = 'dangerEmpty',
  DANGER = 'danger',
  DISABLED = 'disabled',
  DEFAULT = 'default'
}

export enum TextColor {
  SUCCESS = 'success',
  INFO = 'info',
  WARNING = 'warning',
  DANGER = 'danger',
  PRIMARY = 'primary',
  SECONDARY = 'secondary'
}

export enum SvgIconEnum {
  LOGIN = 'login',
  LOGOUT = 'logout',
  ADMIN = 'admin',
  USER = 'user',
  USER_COG = 'userCog',
  SEARCH = 'search',
  SEARCH_PLUS = 'searchPlus',
  HOME = 'home',
  HOME_TWO = 'homeTwo',
  COG = 'cog',
  STORE = 'store',
  SAVE = 'save',
  QUESTION = 'question',
  ARROW_RIGHT = 'arrowRight',
  ARROW_LEFT = 'arrowLeft',
  TEXT_LEFT = 'textLeft',
  UP_AND_DOWN = 'upAndDown',
  EDIT = 'edit',
  ADD = 'add',
  REMOVE = 'remove',
  BACK = 'back',
  EXIT = 'exit',
  EXPAND = 'expand',
  ARROW = 'arrow',
  PAINT = 'paint',
  EXPORT = 'export',
  MORE_OPTIONS = 'moreOptions',
  PLUS = 'plus',
  PLUS_SQUARE = 'plusSquare',
  MINUS = 'minus',
  MINUS_SQUARE = 'minusSquare',
  DOT_CIRCLE = 'dotCircle',
  EYE = 'eye',
  RIGHT_POINT = 'rightPoint',
  DOWN_POINT = 'downPoint',
  CHEVRON_RIGHT = 'chevronRight',
  CHEVRON_LEFT = 'chevronLeft',
  CLOSE = 'close',
  COGS = 'cogs',
  CHECK = 'check',
  SQUARE_EMPTY = 'squareEmpty'
}
